version: '3.9'
services:

  app:
    build:
      context: .
    command: tail -f /dev/null
    environment:
      GENIUS_CLIENT_ACCESS_TOKEN: ${GENIUS_CLIENT_ACCESS_TOKEN}
    ports:
      - '5000:5000'
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      # default database name is postgres, default user is postgres
      POSTGRES_PASSWORD: anji
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:





# access from other service: psql -h db -U postgres
# docker-compose exec db psql -U postgres
# docker-compose run liquibase --defaultsFile=/liquibase/changelog/liquibase.properties --logLevel=info status
